### ISSUE TITLE
Manifest not found

### ISSUE THREAD

**Issue by gianni4711** [gdraheim/docker-copyedit#14]
Hi Guido,

I wanted to remove the /xyz volume from the image1.
But when I process it with your script using:
python docker-copyedit.py from image1 into image2 -vv remove volume /xyz

and start the container i get the message

pulling image2 ...
ERROR: manifest for image2 not found: manifest unknown: manifest unknown

What can I do?

Thanks Uwe

**Comment by gdraheim** [comment]
Why is it pulling "image2" ? That's the data sink. Are you giving the real command line that you are using?

Btw, if it is RHEL8 then you are not using docker but a shim for podman - which is incompatible.

**Comment by gianni4711** [comment]
I'm on debian bullseye.
image2 is the modified image, without the unwanted volume /xyz, isn't it?
Am I wrong?
I modify my docker-compose.yml with it and type "docker-compose up".

**Comment by gianni4711** [comment]
The issue was, that the image2 was tagged with "docker-repo:image2".
Starting the docker stack without the "docker-repo" and tag and push to docker hub later works without error.
Script works perfectly.
Thank you for your quick reply!

**Comment by gdraheim** [comment]
I have created a local-repo check and a testcase "test_990" but I can not reproduce the problem.
