### ISSUE TITLE
can't set architecture variant

### ISSUE THREAD

**Issue by paleozogt** [gdraheim/docker-copyedit#16]
docker-copyedit doesn't allow us to change the architecture "variant" metadata.

For example,
```bash
$ docker inspect arm32v7/ubuntu | jq -r .[].Variant
v7

$ ./docker-copyedit.py FROM arm32v7/ubuntu into foo set variant foo
ERROR:edit:unknown edit command starting with set variant
```

**Comment by gdraheim** [comment]
| ./docker-copyedit.py FROM arm32v7/ubuntu into arm32v7/ubuntu:v8 set variant v8
| docker inspect arm32v7/ubuntu:v8 | jq -r .[].Variant
v8

**Comment by paleozogt** [comment]
The fix is working for me. :+1:
