### ISSUE TITLE
Question: Is the history modification playing a role in image health

### ISSUE THREAD

**Issue by jeffsaremi** [gdraheim/docker-copyedit#22]
THis is only a question.
I wanted to know the significance of this
https://github.com/gdraheim/docker-copyedit/blob/master/docker-copyedit.py#L713-L715
And if adding to the history is helping with properly formatting the tarball for `load`ing the image?
Thanks

**Comment by gdraheim** [comment]
No, that's entry in the metadata, not in a layer-tar.

**Comment by jeffsaremi** [comment]
Thank you Guido!
