### ISSUE TITLE
Removing ports doesn't work

### ISSUE THREAD

**Issue by smiller171** [gdraheim/docker-copyedit#3]
I've tried

`/docker-copyedit.py FROM nginx:alpine INTO nginx:noexpose REMOVE PORT 80`
`/docker-copyedit.py FROM nginx:alpine INTO nginx:noexpose remove all ports`
Both create a new container, but without the EXPOSE removed

```bash
docker inspect nginx:noexpose | jq '.[].ContainerConfig.ExposedPorts'
{
  "80/tcp": {}
}
```

**Comment by gdraheim** [comment]
please check the latest version, it seems to be fixed.

I don't know what it preferring the container_config in this case but as one can loop over all subsection it can be found anyway.

**Comment by gdraheim** [comment]
done.
