### ISSUE TITLE
speed up docker save process

### ISSUE THREAD

**Issue by bigdataolddriver** [gdraheim/docker-copyedit#8]
the tar file generated from "docker save" is optionally keeped by the control of  KEEPDIR , which I understand mostly  for  debugging purpose.
but even KEEPDIR =0,  the tar file is always saved on disk, only deleted afterwards
I am a bit impatient and did following patch , pipe-lining with tee , to save disk IO, save time

23c23
< KEEPDIR = 1
---
> KEEPDIR = 0
251,256c251,254
<         if KEEPDIR >= 2:
<             cmd = "docker save {inp} |tee {inputfile}|tar x -f - -C {datadir}"
<             sh(cmd.format(**locals()))
<         else:
<             cmd = "docker save {inp} |tar x -f - -C {datadir}"
<             sh(cmd.format(**locals()))
---
>         cmd = "docker save {inp} -o {inputfile}"
>         sh(cmd.format(**locals()))
>         cmd = "tar xf {inputfile} -C {datadir}"
>         sh(cmd.format(**locals()))
280,284c278,282
< #        if KEEPDIR >= 2:
< #            logg.warning("keeping %s", inputfile)
< #        else:
< #            if os.path.exists(inputfile):
< #                os.remove(inputfile)
---
>         if KEEPDIR >= 2:
>             logg.warning("keeping %s", inputfile)
>         else:
>             if os.path.exists(inputfile):
>                 os.remove(inputfile)

**Comment by gdraheim** [comment]
Sorry for the late answer. You are right, the default should be to not create a saved.tar but to have the files unpacked from a pipe. 

However I wanted to have it differently which took a while. So the new version of docker-edit.py can select the keep-options seperately (backed with tests now).
